default_config:

logger:
  default: error
  logs:
    renault_api: debug
    custom_components.renault: debug

# If you need to debug uncommment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:
