name: Release

on:
  push:
    branches:
      - main
      - master
      - test

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Publish the release notes
        uses: release-drafter/release-drafter@v5.12.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
